const postcssPresetEnv = require('postcss-preset-env');
const postcssCustomMedia = require('postcss-custom-media');
const header = require('postcss-header');
const nano = require('cssnano');

module.exports = {
  plugins: [
    header({
      header: `/*! THIS FILE IS AUTOGENERATED, PLEASE DO NOT EDIT DIRECTLY. */`
    }),
    require('postcss-import')(),
    postcssCustomMedia(),
    postcssPresetEnv({ stage: 0 }),
    nano()
  ]
};
